POST https://localhost:7062/api/account/Register HTTP/1.1
content-type: application/json

{
    "userName": "test",
    "email": "test@test.com",
    "password": "test"
}

###

POST https://localhost:7062/api/account/Login HTTP/1.1
content-type: application/json

{
    "userName": "test",
    "password": "test"
}

###

PUT https://localhost:7062/api/card/CreateCardSet HTTP/1.1
content-type: application/json

{
    "name": "testset"
}

###

GET https://localhost:7062/api/card/GetCardSets HTTP/1.1

###

GET https://localhost:7062/api/card/GetCardSet/1 HTTP/1.1

###

PATCH https://localhost:7062/api/card/EditCardSet HTTP/1.1
content-type: application/json

{
    "setId": 1,
    "name": "testsetedit"
}

###

DELETE https://localhost:7062/api/card/DeleteCardSet/1 HTTP/1.1

###

PUT https://localhost:7062/api/card/CreateCards HTTP/1.1
content-type: application/json

{
    "setId": 1,
    "cards": [
        {
            "frontValue": "front1",
            "backValue": "back1"
        },
        {
            "frontValue": null,
            "backValue": null
        },
        {
            "frontValue": "front3",
            "backValue": "back3"
        }
    ]
}

###

GET https://localhost:7062/api/card/GetCardsForSet/1 HTTP/1.1

###

PATCH https://localhost:7062/api/card/EditCards HTTP/1.1
content-type: application/json

{
    "setId": 1,
    "cards": [
        {
            "id": 1,
            "frontValue": "test edit 1",
            "backValue": "test edit back"
        },
        {
            "id": 3,
            "frontValue": "test edit 2",
            "backValue": null
        }
    ]
}

###

DELETE https://localhost:7062/api/card/DeleteCards HTTP/1.1
content-type: application/json

{
    "setId": 1,
    "cards": [
        {
            "id": 1
        },
        {
            "id": 2
        }
    ]
}